image:
  repository: yakworks/sftp
  tag: latest
  pullPolicy: IfNotPresent

env: []

service:
  type: LoadBalancer
  port: 3333

# sasdata => Echange pour la DATAWIZ (G2, NEPTUNE)

externalTrafficPolicy: Local