apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sftp.name" . }}
    helm.sh/chart: {{ include "sftp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.azureLoadBalancer.enable }}
    
      {{- if .Values.azureLoadBalancer.isexternal }}
        
        service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.azureLoadBalancer.ressourceGroupIpLoadBalancer }}
      
          

  #      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

        service.beta.kubernetes.io/azure-pip-name: {{.Values.azureLoadBalancer.ipNameLoadBalancer }}
      {{- else }}
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      {{- end }} 

      {{- if and .Values.service.loadBalancerIp (eq .Values.service.type "LoadBalancer") }}
        service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.service.loadBalancerIp}}
      {{- end }}
    {{- end }}    
spec:
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy}}
  {{- end }} 
  {{- if and .Values.service.loadBalancerIp (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIp }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "sftp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
