apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sftp.name" . }}
    helm.sh/chart: {{ include "sftp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.AzureLoadBalancerExternal.enable }}
    {{- if .Values.AzureLoadBalancerExternal.ressourceGroupIpLoadBalancer }}
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.AzureLoadBalancerExternal.ressourceGroupIpLoadBalancer }}
    {{- end }}
    {{- if .Values.AzureLoadBalancerExternal.ipLoadBalancer}}
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.AzureLoadBalancerExternal.ipLoadBalancer}}
    {{- end }}
    {{- if .Values.AzureLoadBalancerExternal.ipNameLoadBalancer }}
    service.beta.kubernetes.io/azure-pip-name: {{.Values.AzureLoadBalancerExternal.ipNameLoadBalancer }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.externalTrafficPolicy}}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy}}
  {{- end }} 
  {{- if and .Values.service.loadBalancerIp (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIp }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "sftp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
