apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: 3306
