{{ if .Values.certManager.enabled }}
{{ if ne .Values.replicaCount 1.0 }}
{{ fail "cert-manager only supported for a single replica" }}
{{/* if gt .Values.replicaCount 1 */}}{{ end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "nifi-registry.fullname" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "nifi-registry.fullname" $ }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  duration: {{ $.Values.certManager.caDuration }}
  renewBefore: 5m1s
  commonName: {{ template "nifi-registry.fullname" $ }}-ca.{{ $.Release.Namespace }}.svc.{{ $.Values.certManager.clusterDomain }}
  subject:
    organizationalUnits:
    - "NiFi Registry"
  secretName: {{ template "nifi-registry.fullname" $ }}-ca
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: {{ template "nifi-registry.fullname" $ }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "nifi-registry.fullname" $ }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ template "nifi-registry.fullname" $ }}-ca
{{ if .Values.certManager.clientCommonName }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "nifi-registry.fullname" $ }}-client
  namespace: {{ $.Release.Namespace }}
spec:
  duration: {{ $.Values.certManager.certDuration }}
  commonName: {{ .Values.certManager.clientCommonName }}
  subject:
    organizationalUnits:
    - NiFi Registry
  secretName: {{ template "nifi-registry.fullname" $ }}-client
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - data encipherment
    - key agreement
    - server auth
    - client auth
  issuerRef:
    name: {{ template "nifi-registry.fullname" $ }}-ca
    kind: Issuer
{{/* if .Values.certManager.clientCommonName */}}{{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "nifi-registry.fullname" $ }}-0
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ template "nifi-registry.fullname" . }}-0.{{ template "nifi-registry.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.certManager.clusterDomain }}
  subject:
    organizationalUnits:
    - NiFi Registry
  secretName: {{ template "nifi-registry.fullname" $ }}-0
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - data encipherment
    - key agreement
    - server auth
    - client auth
  dnsNames:
{{ toYaml $.Values.certManager.additionalDnsNames | indent 4 }}
    - {{ template "nifi-registry.fullname" $ }}.{{ .Release.Namespace }}.svc
    - {{ template "nifi-registry.fullname" $ }}.{{ .Release.Namespace }}.svc.{{ .Values.certManager.clusterDomain }}
    - {{ template "nifi-registry.fullname" $ }}-0.{{ template "nifi-registry.fullname" $ }}-headless.{{ .Release.Namespace }}.svc
    - {{ template "nifi-registry.fullname" $ }}-0.{{ template "nifi-registry.fullname" $ }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.certManager.clusterDomain }}
  issuerRef:
    name: {{ template "nifi-registry.fullname" $ }}-ca
    kind: Issuer
{{/* if .Values.certManager.enabled */}}{{ end }}
