apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mayan.fullname" . }}-flower
spec:
{{- if not .Values.flower.autoscaling.enabled }}
  replicas: {{ .Values.flower.replicaCount }}
{{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mayan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: flower
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "mayan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: flower
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - run_celery
            - "flower{{ if .Values.flower.auth.enabled }} --basic_auth={{- range $key, $val := .Values.flower.auth.accounts -}}{{ range $username, $password := $val }}{{ $username }}:{{ $password }},{{- end -}}{{- end -}}{{- end -}}{{- if .Values.flower.urlPrefix }} --url_prefix={{ .Values.flower.urlPrefix }}{{- end }}"
          envFrom:
            - secretRef:
                name: {{ include "mayan.secretsName" . }}
            - configMapRef:
                name: {{ include "mayan.configMapName" . }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          volumeMounts:
            - name: mayan-media
              mountPath: /var/lib/mayan
            - name: mayan-tmp
              mountPath: /tmp
      volumes:
        - name: mayan-media
          persistentVolumeClaim:
            claimName: {{ include "mayan.persistentVolumeClaimName" . }}
        - name: mayan-tmp
          emptyDir: {}
