{{- if .Values.mellon.enabled -}}
# Defines the ingress for the alfresco content repository
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-repository
  labels:
    app: {{ template "content-services.shortname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.repository.ingress.annotations | indent 4 }}
spec:
  rules:
  {{ $external := .Values.externalHost }}
  {{- if $external }}
  - host: {{ tpl $external $ }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /mellon
        backend:
          serviceName: {{ template "content-services.shortname" $ }}-apache-mellon
          servicePort: 80
      {{- range .Values.mellon.protected_routes }}
      - path: {{ .path }}
        backend:
          serviceName: {{ template "content-services.shortname" $ }}-apache-mellon
          servicePort: 80
      {{- end -}}
      {{ range .Values.mellon.allowed_routes }}
      - path: {{ .path }}
        backend:
          serviceName: {{ template "content-services.shortname" $ }}-apache-mellon
          servicePort: 80
      {{- end -}}
  {{- if .Values.repository.ingress.tls }}
  tls:
{{ toYaml .Values.repository.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
