apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cronjob.fullname" . }}
  labels:
    app: {{ template "cronjob.name" . }}
{{ include "cronjob.labels" . | indent 4 }}
   {{- with .Values.metadata.labels }}
{{ toYaml .Values.metadata.labels | indent 4 }}
   {{- end}}
spec:
  schedule: "{{ .Values.schedule }}"
  {{{- if and (semverCompare">=1.27.0" $.Capabilities.KubeVersion.Version) .Values.timeZone }}
  timeZone: {{ .Values.timeZone }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    metadata:
      labels:
        app: {{ template "cronjob.name" . }}
        chart: {{ template "cronjob.chart" . }}
        cronjob-name: {{ template "cronjob.fullname" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"      
    {{- with .Values.jobTemplate.metadata.labels }}
{{ toYaml .Values.jobTemplate.metadata.labels | indent 4 }}
      {{- end}}
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          {{- if .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- range $secret := .Values.image.pullSecrets }}
            - name: {{ $secret }}
            {{- end }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: {{ template "cronjob.fullname" . }}
              image: {{ template "cronjob.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
              {{- with .Values.resources }}
              resources:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.env }}
              env:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.command }}
              command:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
{{ toYaml . | indent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
