apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "superset.name" . }}
    helm.sh/chart: {{ include "superset.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  superset_config.py: |+
    import os

    # Dynamically set simple superset configuration from environment variable
    for env_var in os.environ:
        if env_var.startswith('SUPERSET__'):
            globals()[env_var[10:]] = os.environ[env_var]
