apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: {{ include "mayan.fullname" . }}-frontend
spec:
{{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mayan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "mayan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- include "deployments.affinity" (dict "root" $ "local" $.Values.frontend) | indent 6 }}
      containers:
        - args:
            - run_frontend
          {{- include "containers.env" . | indent 10 }}
          envFrom:
            - secretRef:
                name: {{ include "mayan.secretsName" . }}
            - configMapRef:
                name: {{ include "mayan.configMapName" . }}
          {{- include "containers.image" . | nindent 10 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-frontend
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          volumeMounts:
            {{- if $.Values.persistence.core.enabled }}
            - name: mayan-media
              mountPath: /var/lib/mayan
            {{- end }}
            - name: mayan-tmp
              mountPath: /tmp
      {{- include "containers.imagePullSecrets" . | indent 6 }}
      volumes:
        {{- if $.Values.persistence.core.enabled }}
        - name: mayan-media
          persistentVolumeClaim:
            claimName: {{ include "pvcs.persistentVolumeClaimName" . }}
        {{- end }}
        - name: mayan-tmp
          emptyDir: {}
