{{- if .Values.letsencrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "mayan.tlsUniqueName" . }}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.letsencrypt.email }}
    {{- if .Values.letsencrypt.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ include "mayan.tlsSecretUniqueName" . }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: {{ .Values.letsencrypt.issuerHTTPSolverIngressClass }}
      selector:
        dnsNames:
        - '{{ .Values.letsencrypt.domain }}'
{{- end }}
