apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mayan.secretsName" . }}
type: Opaque
stringData:
{{- include "mayan.secrets.managed" . | nindent 2 -}}
{{- include "mayan.secrets.unmanaged" . | nindent 2 -}}
