apiVersion: spv.no/v2beta1

targetSecrets: []
    # ================
    # To map multiple single keys to a secret, use the 'mappedKeys' property
    # ================
    # - keyVaultSource: my-keyvault
    #   secretNameTarget: my-secret
    #   mappedKeys: 
    #     user: user-login # object name in key vault mapped to key in secret
    #     password: password
    # ================
    # To map multiple keys from a single secret, use the 'multiKeyValue' property
    # ================
    # - keyVaultSource: my-keyvault 
    #   secretNameTarget: my-secret-multi
    #   multiKeyValue: db-values # object name in key vault
    #   contentType: 'application/x-json' # 'application/x-json' or 'application/x-yaml'
             