apiVersion: v2
description: A Helm chart Providing the required Alfresco infrastructure for the Digital
  Business Platform. This includes activemq, alfresco-identity-service, nginx-ingress
  and a persistent volume to use with the DBP chart.
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
name: alfresco-infrastructure
version: 4.1.1
dependencies:
  - name: activemq
    version: ^1.1.1
    repository: https://kubernetes-charts.alfresco.com/stable
    condition: alfresco-infrastructure.activemq.enabled
  - name: alfresco-identity-service
    version: 1.1.0
    condition: alfresco-infrastructure.alfresco-identity-service.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
  - name: nginx-ingress
    condition: alfresco-infrastructure.nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.14.0
