apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.doc.fullname" . }}
  labels:
    {{- include "smartshape.doc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.doc.service.type }}
  ports:
    - port: {{ .Values.doc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.doc.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.doc.selectorLabels" . | nindent 4 }}
