apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
