apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-account-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-account-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-annotation-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-annotation-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-file-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-file-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-live-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-live-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-scene-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-scene-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-update-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-update-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartshape.server.fullname" . }}-webhook-api
  labels:
    {{- include "smartshape.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "smartshape.server.selectorLabels" . | nindent 4 }}
    smartshape/api: smartshape-webhook-api


