{{- if .Values.ssh.userPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openssh-server.name" . }}
    helm.sh/chart: {{ include "openssh-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  user-password: {{ .Values.ssh.userPassword | b64enc | quote }}
{{- end }}