apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb-relay.fullname" . }}
  labels:
    app: {{ template "influxdb-relay.name" . }}
    chart: {{ template "influxdb-relay.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.service.annotations }}
annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: http-api
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "influxdb-relay.name" . }}
    release: {{ .Release.Name | quote }}
