apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb-relay.fullname" . }}-headless
  labels:
    app: {{ template "influxdb-relay.name" . }}
    chart: {{ template "influxdb-relay.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-api
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "influxdb-relay.name" . }}
    release: {{ .Release.Name | quote }}
