apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.operator.component }}
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/part-of: {{ .Values.operator.partOf }}
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.operator.component }}
        app.kubernetes.io/name: {{ .Values.operator.name }}
        app.kubernetes.io/part-of: {{ .Values.operator.partOf }}
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
        name: {{ .Values.operator.containerName }}
        ports:
        - containerPort: {{ .Values.operator.ports.metrics }}
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.operator.resources.limits.cpu }}
            memory: {{ .Values.operator.resources.limits.memory }}
          requests:
            cpu: {{ .Values.operator.resources.requests.cpu }}
            memory: {{ .Values.operator.resources.requests.memory }}
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.operator.terminationGracePeriodSeconds }}
