{{- if not .Values.existingSecret }}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ default "SuperSecret" .Values.env.password | b64enc | quote }}
{{- if .Values.serverDefinitions.enabled }}
  servers.json: {{ include "pgadmin.serverDefinitions" . | b64enc | quote }}
{{- end }}
{{- if .Values.pgPassFile.enabled }}
  pgpassfile: {{ .Values.pgPassFile.content | b64enc | quote }}
{{- end }}
{{- end }}
