apiVersion: v1
description: A Helm chart for Symfony application deployment. You can deploy worker or cronjob with the same chart
name: symfony
version: 2.3.6
icon: https://symfony.com/images/v5/pictos/home-main-illu.svg
