apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
    app: {{ template "influxdb.name" . }}
{{ include "influxdb.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.serviceName }}
  template:
    metadata:
      {{- if .Values.annotations }}
      annotations:
        {{- range .Values.annotations }}
          {{ .key }}: '{{ .value }}'
          {{- end }}
      {{- end }}
      labels:
        app: {{ template "influxdb.name" . }}
{{ include "influxdb.labels" . | indent 8 }}
    spec:
{{- if or .Values.podAntiAffinity .Values.affinity }}
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if eq .Values.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .Values.podAntiAffinityTopologyKey }}
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "influxdb.name" . }}
{{- else if eq .Values.podAntiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: {{ .Values.podAntiAffinityTopologyKey }}
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "influxdb.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: influxdb
          image: {{ template "influxdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 8 }}
{{- end }}
          ports:
            - containerPort: 8086
              name: http-api
{{- if .Values.backup.enable }}
            - containerPort: {{ .Values.backup.port }}
              name: http-api-backup
{{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
{{- if .Values.metrics.enabled }}
        - name: influxdb-exporter
          image: {{ template "influxdb.metrics.image" . }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
          ports:
            - name: metrics
              containerPort: 9273
          resources:
{{ toYaml .Values.metrics.resources | indent 12 }}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
{{- end }}
      volumes:
{{- if .Values.config }}
        - name: {{ .Values.config.name }}
          configMap:
{{ toYaml .Values.config.configMap | indent 16 }}
{{- end }}
{{- if or (.Files.Glob "files/docker-entrypoint-initdb.d/*.{sh,sql,sql.gz}") .Values.initdbScriptsConfigMap .Values.initdbScripts }}
        - name: custom-init-scripts
          configMap:
            name: {{ template "influxdb.initdbScriptsCM" . }}
{{- end }}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ template "influxdb.name" . }}
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
{{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
