{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "jobFullname" . }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    symfony.io/type: job
  {{- if .Values.metadata.labels }}
{{ toYaml .Values.metadata.labels | indent 4 }}
   {{- end}}
  annotations:
{{ .Values.job.annotations | toYaml | indent 4 }}

spec:
  completions: 1
  parallelism: 1
  backoffLimit: 6
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      name: "{{ template "jobFullname" . }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        symfony.io/type: job
    {{- if .Values.template.metadata.labels }}
{{ toYaml .Values.template.metadata.labels | indent 4 }}
    {{- end}}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range $secret := .Values.image.pullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      {{- end }}
      containers:
        - name: job
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
{{ .Values.job.cmd | toYaml | indent 12 }}
          args:
{{ .Values.job.args | toYaml | indent 12 }}
          {{- if .Values.env }}
          env:
            {{- range $key, $env := .Values.env.container }}
            - name: {{ $env.name }}
             {{- if $env.typeSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretKeyRef.name }}
                  key: {{ $env.secretKeyRef.key }}

            {{- else if $env.valueFrom }}
              {{- if $env.valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.valueFrom.secretKeyRef.name }}
                  key: {{ $env.valueFrom.secretKeyRef.key }}
              {{- else if $env.valueFrom.fieldRef }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $env.valueFrom.fieldRef.fieldPath }}
              {{- end }}
            {{- else }}
              value: {{ $env.value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraEnv }}
            {{- range $env := .Values.extraEnv }}
            - name: {{ $env.name }}
             {{- if $env.typeSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secretKeyRef.name }}
                  key: {{ $env.secretKeyRef.key }}
            {{- else if $env.valueFrom }}
              {{- if $env.valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.valueFrom.secretKeyRef.name }}
                  key: {{ $env.valueFrom.secretKeyRef.key }}
              {{- else if $env.valueFrom.fieldRef }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $env.valueFrom.fieldRef.fieldPath }}
              {{- end }}
            {{- else }}
              value: {{ $env.value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
{{- end }}