apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    app: {{ include "memcached.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11211
      protocol: TCP
      name: memcached
  selector:
    app: {{ include "memcached.name" . }}
