{{- if .Values.ooi.enabled }}
apiVersion:  {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "content-services.shortname" . }}-ooi-service
  labels:
    {{- include "ooi-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /ooi-service
{{- if .Values.ooiService.extraAnnotations }}
{{ toYaml .Values.ooiService.extraAnnotations | indent 4 }}
{{- end }}
{{- if not .Values.mellon.enabled -}}
spec:
  {{- if .Values.ooiService.ingress.tls }}
  tls:
    {{- range .Values.ooiService.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ooiService.ingress.hostName }}
  - host: {{ tpl .Values.ooiService.ingress.hostName $ }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: {{ .Values.ooiService.ingress.path }}
        {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion  }}
          serviceName: {{ template "content-services.shortname" . }}-ooi-service
          servicePort: {{ .Values.ooiService.service.externalPort }}
          {{- else  }}
          service:
            name: {{ template "content-services.shortname" . }}-ooi-service
            port: 
              number: {{ .Values.ooiService.service.externalPort }}
          {{- end }}
{{- end }}
{{- end -}}
