{{- if .Values.mellon.enabled -}}
# Defines the service for the alfresco content repository app
apiVersion: v1
kind: Service
metadata:
  name: {{ template "content-services.shortname" . }}-apache-mellon
  labels:
    app: {{ template "content-services.shortname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: apache-mellon
spec:
  type: {{ .Values.repository.service.type }}
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: {{ template "content-services.shortname" . }}-apache-mellon
    release: {{ .Release.Name }}
{{- end -}}
