apiVersion: v2
name: alfresco-content-services-community
version: 4.0.4
appVersion: 6.2.1-ea
description: A Helm chart for deploying Alfresco Content Services Community
keywords:
- community
- alfresco community
- content
- content services
- alfresco
- alfresco content services
home: https://www.alfresco.com
sources:
- https://github.com/Alfresco/acs-community-deployment
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
dependencies:
- name: postgresql
  version: 0.9.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: alfresco-search
  version: 1.0.3
  repository: https://raw.githubusercontent.com/3slab/helm-charts/master/repo
  condition: alfresco-search.enabled
- name: alfresco-infrastructure
  version: 4.1.1
  condition: alfresco-content-services.alfresco-infrastructure.enabled
  repository: https://raw.githubusercontent.com/3slab/helm-charts/master/repo